ARG NODE_VERSION=20.19.5
FROM node:${NODE_VERSION}-alpine3.22

ENV NODE_ENV=development

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN mkdir -p /app/uploads /app/logs

EXPOSE 8000

CMD ["npm", "run", "dev"]